### ISSUE TITLE
DNS removal bug

### ISSUE THREAD

**Issue by ivdeveloper86** [batchar2/fptn#175]
After using FPTN Client 0.3.32 on a Windows 11 system, the DNS entry in the network connection (TCP/IPv4) is removed. This issue didn't occur with the older version 0.3.29.

**Comment by batchar2** [comment]
Thank you for your report! Could you please provide screenshots or additional details so I can check the issue and reproduce it on my system?

**Comment by ivdeveloper86** [comment]
> Thank you for your report! Could you please provide screenshots or additional details so I can check the issue and reproduce it on my system?

<img width="216" height="260" alt="Image" src="https://github.com/user-attachments/assets/e6ba8dc6-11e6-4017-a1a8-5d9359e2d831" />

<img width="454" height="260" alt="Image" src="https://github.com/user-attachments/assets/eb28bffa-b341-47ac-87a3-b897bf6d4943" />

[fptn-client-gui.log](https://github.com/user-attachments/files/24400102/fptn-client-gui.log)

**Comment by batchar2** [comment]
Thank you!

**Comment by batchar2** [comment]
Hello!

I've fixed your issue:
https://github.com/batchar2/fptn/pull/202

This fix will be included in the next release.

**Comment by batchar2** [comment]
Of course, a .ru website will show you a Russian location, because when traffic splitting is enabled, Russian sites are accessed directly. This is a specific feature that allows Russian websites to work, because by default all .ru domains are routed directly.

<img width="699" height="719" alt="Image" src="https://github.com/user-attachments/assets/c3a73ce9-e7e5-46f3-b1fb-c1162e5e763d" />

To check your real IP address, you should use a non-.ru website (for example, try https://whatismyipaddress.com/
 ) or turn off traffic splitting in the settings.

**Comment by ivdeveloper86** [comment]
FPTN Client 0.3.40
The problem is not completely solved, if I use FPTN Client and reboot the PC, after loading the DNS will be empty and the Internet will not work.
[logs.zip](https://github.com/user-attachments/files/28176299/logs.zip)
@batchar2

**Comment by ivdeveloper86** [comment]
Version 0.3.41 has the same problem
